SPARK-48812 Remove group write permission from files included in .deb (#15)
Previously with a deb built from this repo, some files had the group write permission flag set which caused the expressway to complain:
2018-12-11T09:28:02.266+00:00 supervisor: UTCTime="2018-12-11 09:28:02,266" Module="developer.supervisor" Level="ERROR" CodeLocation="firestarter(197)" Error="Unexpected output" Process="/sbin/logrotated" Detail="error: Ignoring hybridserviceslog-rotate.conf because of bad file mode - must be 0644 or 0444. "

Although this no longer seemed to be the case when I built the deb, no intentional change was made to fix this so we're not fully sure what happened. To prevent this occurring again, this commit adds a build step that removes the group read permission for all files that will be included in the deb. It then asserts no files were found with that permission, and fails the build if this is not the case.

Also removing the old swpkg.lst file as it's no longer needed.

Jira link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-48812

diff --git a/jenkins/packaging_methods b/jenkins/packaging_methods
--- a/jenkins/packaging_methods
+++ b/jenkins/packaging_methods
@@ -176,6 +176,18 @@ generate_debian_version(){
     sed -i "s/BUILD_VERSION/${BUILD_VERSION}/" ${CONTROL_FILE}
 }
 
+remove_group_write_permissions(){
+    chmod -R g-w ./debian
+
+    num_found=$(find ./debian -perm -g=w -type f | wc -l)
+    if [ $num_found -ne 0 ]; then
+        echo "Files exist with the group write permission set - FAILING BUILD"
+        echo "Infringing files are:"
+        find ./debian -perm -g=w -type f
+        exit 1
+    fi
+}
+
 package_debian(){
     # Build a debian from a debian-bnary, control, and data tars.
     echo "package_debian: Building the control, data tars and debian package"
