Adding first Jenkins file and Dockerfile (#3)
* Add first basic Jenkinsfile, dockerfile and minor bash tweaks

diff --git a/jenkins/packaging_methods b/jenkins/packaging_methods
--- a/jenkins/packaging_methods
+++ b/jenkins/packaging_methods
@@ -3,9 +3,9 @@
 PYTHON=python
 TOOLCHAIN_PYTHON=/tandberg/system/toolchain/x86_64_gcc-7.3.0_glibc-2.28_i686-host-linux-gnu-5/bin/python
 
-if [ -f $TOOLCHAIN_PYTHON  ]; then
+if [[ -f ${TOOLCHAIN_PYTHON}  ]]; then
     # Use the local toolchain python if it's available
-    PYTHON=$TOOLCHAIN_PYTHON
+    PYTHON=${TOOLCHAIN_PYTHON}
 fi
 
 clean_working_directory(){
@@ -16,20 +16,20 @@ clean_working_directory(){
 install_python_component(){
     echo "install_python_component: Compiling and installing python package"
     # Force install into debian directory, overwiritng any existing files
-    $PYTHON setup.py install --force --root=debian/data/ -O0 --compile
+    ${PYTHON} setup.py install --force --root=debian/data/ -O0 --compile
 }
 
 dublicate_and_symlink_transform(){
     TRANSFORM_DIR=debian/data/tandberg/upgrade/cdbtransforms.d
-    TRANSFORM_FILE=$TRANSFORM_DIR/cmgmt_transform.py
+    TRANSFORM_FILE=${TRANSFORM_DIR}/cmgmt_transform.py
     POSTINTSTALL_DIR=debian/data/tandberg/etc/postinstall-scripts.d
-    [ ! -d $POSTINTSTALL_DIR ] && echo "Creating ${POSTINTSTALL_DIR}" && mkdir -p $POSTINTSTALL_DIR
-    [ -f $TRANSFORM_FILE ] && echo "Found and copying cmgmt_transform.py" && cp $TRANSFORM_FILE $POSTINTSTALL_DIR/cmgmt-transform
-    [ -f $POSTINTSTALL_DIR/cmgmt-transform ] && chmod 0755 $POSTINTSTALL_DIR/cmgmt-transform
+    [[ ! -d ${POSTINTSTALL_DIR} ]] && echo "Creating ${POSTINTSTALL_DIR}" && mkdir -p ${POSTINTSTALL_DIR}
+    [[ -f ${TRANSFORM_FILE} ]] && echo "Found and copying cmgmt_transform.py" && cp ${TRANSFORM_FILE} ${POSTINTSTALL_DIR}/cmgmt-transform
+    [[ -f ${POSTINTSTALL_DIR}/cmgmt-transform ]] && chmod 0755 ${POSTINTSTALL_DIR}/cmgmt-transform
 
     # Create a symlink in postinstall.current.d, call 80-cmgmt-transform,
     # and have it point at ../postinstall-script/80-cmgmt-transform
-    [ ! -d debian/data/tandberg/etc/postinstall.current.d ] && echo "Creating debian/data/tandberg/etc/postinstall.current.d" && mkdir -p debian/data/tandberg/etc/postinstall.current.d
+    [[ ! -d debian/data/tandberg/etc/postinstall.current.d ]] && echo "Creating debian/data/tandberg/etc/postinstall.current.d" && mkdir -p debian/data/tandberg/etc/postinstall.current.d
     pushd debian/data/tandberg/etc/postinstall.current.d
     ln -s ../postinstall-scripts.d/cmgmt-transform 80-cmgmt-transform
     popd
@@ -38,7 +38,7 @@ dublicate_and_symlink_transform(){
 sanitize_debian_package(){
     echo "sanitize_debian_package: Removing unwanted files from package"
     # Delete egg info directory from debian pacakge
-    if [ -d debian/data/ ]; then
+    if [[ -d debian/data/ ]]; then
         find debian/data/ -name "management_connector*egg-info" -type d -print | xargs rm -rf {}
         find debian/data/ -name "management_connector*.pth" -print | xargs rm -rf {}
 
@@ -63,7 +63,7 @@ remove_init_py_files(){
 
     for file in $INIT_FILES
     do
-        [ -f $file ] && echo "Found and removing: ${file}" && rm $file
+        [[ -f ${file} ]] && echo "Found and removing: ${file}" && rm ${file}
     done
 }
 
@@ -74,6 +74,7 @@ include_files(){
 
 convert_po_to_mo(){
     msgfmt ./debian/data/tandberg/locale/en_US.utf8/LC_MESSAGES/managementconnector.po -o ./debian/data/tandberg/locale/en_US.utf8/LC_MESSAGES/managementconnector.mo
+    [[ ! -f ./debian/data/tandberg/locale/en_US.utf8/LC_MESSAGES/managementconnector.mo ]] && echo "Localisation failure: Mo file not created" && exit 1
     rm ./debian/data/tandberg/locale/en_US.utf8/LC_MESSAGES/managementconnector.po
 }
 
@@ -83,21 +84,21 @@ generate_symlinks(){
     popd
 
     RC2_DIR=debian/data/etc/rc2.d/
-    [ ! -d $RC2_DIR ] && mkdir -p $RC2_DIR
-    pushd $RC2_DIR
+    [[ ! -d $RC2_DIR ]] && mkdir -p $RC2_DIR
+    pushd ${RC2_DIR}
     ln -s ../init.d/c_mgmt S80c_mgmt
     popd
 
     TANDBERG_ETC_DIR=/tandberg/persistent/fusion/config/
     pushd debian/data/opt/c_mgmt/etc/
-    ln -s $TANDBERG_ETC_DIR config
+    ln -s ${TANDBERG_ETC_DIR} config
     popd
 
     OPT_BIN=/share/python/site-packages/ni/managementconnector
     OPT_TEST=/share/python/site-packages/ni/tests/managementconnector
     pushd debian/data/opt/c_mgmt/
-    ln -s $OPT_BIN bin
-    ln -s $OPT_TEST test
+    ln -s ${OPT_BIN} bin
+    ln -s ${OPT_TEST} test
     popd
 }
 
@@ -108,7 +109,7 @@ install_external_dependencies(){
 package_debian(){
     # Build a debian from a debian-bnary, control, and data tars.
     echo "package_debian: Building the control, data tars and debian package"
-    [ ! -d debian/_build/ ] && mkdir -p debian/_build/
+    [[ ! -d debian/_build/ ]] && mkdir -p debian/_build/
 
     pushd debian/control > /dev/null
     tar czp --owner=root --group=root -f ../_build/control.tar.gz .
@@ -122,9 +123,9 @@ package_debian(){
     ar -r c_mgmt.deb ../debian-binary control.tar.gz data.tar.gz
     popd > /dev/null
 
-    if [ -f debian/_build/c_mgmt.deb ]; then
+    if [[ -f debian/_build/c_mgmt.deb ]]; then
         echo "package_debian: debian/_build/c_mgmt.deb created."
     else
-        echo "package_debian: c_mgmt failed to be created"
+        echo "package_debian: c_mgmt failed to be created" && exit 1
     fi
 }
